<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net462;net472;net48;net481;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0;</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>1.0.4</Version>
        <AssemblyTitle>SecondaryClick.WindowsInput</AssemblyTitle>
        <AssemblyName>System.WindowsInput</AssemblyName>
        <RootNamespace>System.WindowsInput</RootNamespace>
        <PackageId>$(AssemblyTitle)</PackageId>
        <Platforms>x86;x64;ARM64</Platforms>
        <Authors>QL-Win</Authors>
        <Company>QL-Win</Company>
        <RepositoryUrl>https://github.com/QL-Win/SecondaryClick</RepositoryUrl>
        <PackageProjectUrl>https://github.com/QL-Win/SecondaryClick</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>Keyboard Mouse Windows Simulate Simulator SendInput</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>Windows Input Simulator (C# SendInput Wrapper - Simulate Keyboard and Mouse)</Description>
        <PackageIcon>Logo.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <IncludeSymbols>true</IncludeSymbols>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\branding\Logo.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>